### ISSUE TITLE
type tags not working properly

### ISSUE THREAD

**Issue by Socratov** [chisaipete/bestiary#1]
When I try to filter by type I get the following error: 

404

File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

Read the full documentation for more information about using GitHub Pages.

GitHub Status — @githubstatus

**Comment by chisaipete** [comment]
Which type are you clicking on? There is a known tagging issue.

**Comment by Socratov** [comment]
all of the creaturetype tags. 

The CR tags work fine, but the rest are broken

**Comment by chisaipete** [comment]
Oh, fantastic!  That wasn't busted in my local build.  Hmm

**Comment by chisaipete** [comment]
Looks like the rakefile is busted on my end, I'm working on correcting and republishing now.

**Comment by chisaipete** [comment]
I've pushed an update, it looks like the tags are now corrected.  Silly Windows, you really are for kids.  Ruby shellescape didn't play nice with the system calls in the rakefile.
