### ISSUE TITLE
Spellcaster's references to spells should be links

### ISSUE THREAD

**Issue by chisaipete** [chisaipete/bestiary#14]
It would be really slick if you could click on the description of a spell in the monster page and it would open a new tab with the Grimoire spell description.

**Comment by thisboyiscrazy** [comment]
Hasn't http://ephe.github.io/grimoire been taken down?

**Comment by chisaipete** [comment]
You're right, so yes, this should be closed.

**Comment by svmnotn** [comment]
http://thebombzen.github.io/grimoire/ is a fork of it and seems about equivalent, maybe reopen?

**Comment by chisaipete** [comment]
I'm nervous about linking to content that will be easily subject to DMCA takedown.  Also, https://www.dndbeyond.com/ looks like it may be the solution we're all hoping for.  If it's not affordable, I'll consider reopening.
