### ISSUE TITLE
Goristro

### ISSUE THREAD

**Issue by Tubben** [chisaipete/bestiary#32]
The Goristro has a Con of 25, not 15 :)

**Comment by chisaipete** [comment]
Can you submit a pull request? If not, it'll be a bit before I collect more issues to bundle into another update.

**Comment by Tubben** [comment]
Tried it, Seems i am to dumb to make that happen :) 
I just dont have an idea how to edit the file. Came up to the point where he said i can only edit an branch, whatever that is.
Guess i just wait till someone else does it, or you find the time to do it :) Thanks for your great work anyway.

**Comment by chisaipete** [comment]
It's alright, if/when I get a free moment, I'll take care of this.  Thanks

**Comment by ryanhornik** [comment]
I was fixing another thing, so I went ahead and put in the pull request for this too.

**Comment by Tubben** [comment]
Nice, thanks alot. Ich need to learn how to do pull requests also.

**Comment by chisaipete** [comment]
This is now merged into master, it will be published shortly, thanks for your patience! #34
