### ISSUE TITLE
Stat Inconsistency

### ISSUE THREAD

**Issue by JGraeson** [chisaipete/bestiary#36]
I am just updating a local Wild Shape table I use and ran across an inconsistency;

Allosaurus HP is listed in the Bestiary as "60 (6d10+18)", but the average roll (and MM-entry) for these creatures lists "51 (6d10+18)".

(My apologies if this is an SRD/MM issue, I did have a look around, but didn't see anything obvious to indicate this.)

**Comment by chisaipete** [comment]
I'll add this change to my next update since I'm in the code now, but in the future, just submit a Pull Request for any fixes 👍

**Comment by chisaipete** [comment]
#a5e0601db8a1081fd8e58709d60380c1aaacf836
