### ISSUE TITLE
Missing monsters from Basic Rules, MM and Volvo

### ISSUE THREAD

**Issue by fstroth** [chisaipete/bestiary#43]
After comparing the existing entries with the monsters from the Basic Rules, MM and Volvo there are 25 missing. I plan on adding them in the near future. This issue is to keep track of the monsters that are missing/have been added.

- [x] shadow mastiff alpha

Edit 1:
After looking a bit further into is there are only two monsters missing. I will add them later today. 

Edit 2:
Ultraloth was is misspelled should have been Ultroloth, which is already in the database.

**Comment by chisaipete** [comment]
Some of these entries sound familiar, there may be reasons (that I haven't debugged) why the posts aren't generating.

An example, check the _posts directory and you'll see entries for all the faerie dragons.  Now, why they aren't showing up online, I'm not sure.  

Although at first glance, most of these names have special punctuation in them, maybe that's causing them to get borked while Jekyll is running?  Please take a look if you'd like.

**Comment by fstroth** [comment]
Added the Shadow Mastiff Alpha, but i can't push.

**Comment by chisaipete** [comment]
Please submit a pull request.

**Comment by fstroth** [comment]
I get a *Permission denied* when trying to push.

**Comment by johnsonra** [comment]
You'll need to submit a pull request. This video gives a good description of it: https://www.youtube.com/watch?v=YTbRzhQju4c

The pull request part is at about 3:40.

Thanks for contributing!

**Comment by fstroth** [comment]
Thanks for the help.
