### ISSUE TITLE
Looking for a new owner

### ISSUE THREAD

**Issue by chisaipete** [chisaipete/bestiary#52]
For personal reasons I'm no longer interested in maintaining this project.  Please let me know here or in a direct message of some kind if you'd like to help out!   I'd be happy to help someone get set up and get it published on their own gh-pages account.

**Comment by colinloretz** [comment]
@chisaipete as a long time user of this guide to fantastic beasts, I'd be happy to maintain it if no one else steps forward.

**Comment by MrEnigmamgine** [comment]
:( Sorry to see you go @chisaipete .

I don't really know what I'm doing, but if someone will show me the ropes I will be happy to step up and maintain the project.  Otherwise I'm happy to continue contributing on wherever this gets forked to.

**Comment by austinburks** [comment]
Any updates on passing the reins @chisaipete?

**Comment by chisaipete** [comment]
No, I haven't, but there has been some good interest shown in the project since I mentioned handing it off, which is nice.  Depending on how things go, maybe this will be unnecessary? Not sure yet. I'll be sure to keep this up to date!

**Comment by chisaipete** [comment]
I'm going to close, I've found that @Kyrremann 's refactoring has made it much easier to maintain, so I think I'll hold onto the reins for now--I'll be sure to reopen if I want to revisit.
