### ISSUE TITLE
Upgrade Jekyll and use collections

### ISSUE THREAD

**Issue by Kyrremann** [chisaipete/bestiary#58]
I just started looking at this project, and I was wondering why you are building the project with Rake, and not just letting Github do the building automatically when you commit? 

Also, instead of using posts, latest Jekyll lets you add collections. This will save you the hassle with the date. Then you could either just use the monster name, or have an arbitrary number.

If you would like, I can make a PR request with a fix for both. One with the update and cleaned for latest Jekyll, and another PR with monsters as a collection.

**Comment by chisaipete** [comment]
I'll happily accept PRs!  If you check the other issues, you'll notice I'm not actively developing this tool anymore, any enhancements will need to come from users.

**Comment by chisaipete** [comment]
As far as using Rake, that's the build system that I lifted from another project and it just worked.  I didn't bother trying to change or fix it, since it wasn't necessarily broken.

**Comment by Kyrremann** [comment]
Yeah, I saw the other thread, but was a bit unsure. Anyway, I'll make two PR's, and we'll see if you like them.

Okay, custom plugins require some prepossessing for Github. I'll look some more into it. Thanks.
