### ISSUE TITLE
Remove empty categories from all creature listing pages

### ISSUE THREAD

**Issue by chisaipete** [chisaipete/bestiary#63]
![image](https://user-images.githubusercontent.com/458551/56376067-dad9db80-61bb-11e9-90ae-3d0ede13b3b0.png)

_Originally posted by @chisaipete in https://github.com/chisaipete/bestiary/pull/62#issuecomment-484581396_

**Comment by Kyrremann** [comment]
I took a quick look at this one, and it was easy to just show the CR with monster in them, but I'm not sure how to do it with the `Challenge Rating` list.

**Comment by chisaipete** [comment]
Looks good, except the page is hard to read now:

![image](https://user-images.githubusercontent.com/458551/56389614-da9f0780-61de-11e9-94b8-54780c310545.png)
![image](https://user-images.githubusercontent.com/458551/56389695-0cb06980-61df-11e9-9cee-a54d38a79ec6.png)


That's not as clean or readable as:
![image](https://user-images.githubusercontent.com/458551/56389679-fe624d80-61de-11e9-9dd7-58ce2a9194a0.png)
![image](https://user-images.githubusercontent.com/458551/56389734-22be2a00-61df-11e9-84e0-dff89df8bbb1.png)

**Comment by Kyrremann** [comment]
That's a really good point! I'll try to fix that.
