### ISSUE TITLE
Duplicate Creatures

### ISSUE THREAD

**Issue by chisaipete** [chisaipete/bestiary#64]
There still are some duplicate creatures.

_Originally posted by @Kyrremann in https://github.com/chisaipete/bestiary/pull/62#issuecomment-484594202_

**Comment by Kyrremann** [comment]
The list of duplicates

- [ ] Abyssal Wretch
- [ ] Air Elemental Myrmidon
- [ ] Astral Dreadnought
- [ ] Deathlock Wight
- [ ] Derro Savant
- [ ] Duergar Kavalrachni
- [ ] Duergar Soulblade
- [ ] Duergar Stone Guard
- [ ] Duergar Xarrorn
- [ ] Earth Elemental Myrmidon
- [ ] Female Steeder
- [ ] Fire Elemental Myrmidon
- [ ] Fraz-Urb'luu
- [ ] Githyanki Knight
- [ ] Githyanki Warrior
- [ ] Graz'zt
- [ ] Male Steeder
- [ ] Vampiric Mist
- [ ] Water Elemental Myrmidon

**Comment by chisaipete** [comment]
Are the posts completely identical, or are there important differences?

**Comment by Kyrremann** [comment]
There are differences, can't remember what, but enough that I didn't know
how to merge them as I don't have access to the official resources.

Mvh
Kyrre Havik Eriksen
Gøteborggata 26
0566 Oslo
47859817

fre. 19. apr. 2019, 18:00 skrev Connor Petersen <notifications@github.com>:

**Comment by chisaipete** [comment]
Okay, so this is an interesting issue.  Some of these are cases where the same monster has different stats and abilities depending on which book it was published in.  Hmm.

**Comment by Kyrremann** [comment]
Oh, maybe we could add the book shortname in the title? `MonsterName [Book]` for example.

**Comment by chisaipete** [comment]
I was thinking about this over the weekend: I think we should do something
like: MonsterName A, and then distinguishing between the revisions using
the tags below the block.  I'm not sure I want to put anything more than a
revision code in the title.

**Comment by Kyrremann** [comment]
That's a good idea. The tags already have the book in them, so we could just add the revision letter and be set.

**Comment by Kyrremann** [comment]
Since I'm creating PR later tonight, I can fix this too.
Do you want it to be `Abyssal Wretch A` and `Abyssal Wretch B`?

**Comment by chisaipete** [comment]
Yeah! That'd be great.  I regrettably haven't had a chance to sit down and
sort the duplicates out quite yet.

**Comment by Kyrremann** [comment]
I've had another look at this, and some of the differences are pretty subtle.

```
$ diff waterelementalmyrmidon.md water-elemental-myrmidon.md
4,5c4
< tags: [medium, elemental, cr7, mordenkainens-tome-of-foes]
< page_number: 203
---
> tags: [medium, elemental, cr7, elemental-evil]
16c15
< senses: "darkvision 60 ft., passive Perception 10"
---
> senses: "darkvision 60 ft."
23c22
< **Damage Resistances** acid; bludgeoning, piercing, and slashing from nonmagical attacks
---
> **Damage Resistances** acid; bludgeoning, piercing, and slashing from nonmagical weapons
33c32
< ***Trident*** Melee or Ranged Weapon Attack: +7 to hit, reach 5 ft. or range 20/60 ft., one target. Hit: 7 (1d6 + 4) piercing damage, or 8 (1d8 + 4) piercing damage if used with two hands to make a melee attack.
---
> ***Trident.*** Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 7 (1d6 + 4) piercing damage.
35c34
< ***Freezing Strikes (Recharge 6)*** The myrmidon uses Multiattack. Each attack that hits deals an extra 5 (1d10) cold damage. A target that is hit by one or more of these attacks has its speed reduced by 10 feet until the end of the myrmidon's next turn.
---
> ***Freezing Strikes (Recharge 6).*** The myrmidon uses Multiattack. Each attack that hits deals an extra 5 (1d10) cold damage, and the target's speed is reduced by 10 feet until the end of the myrmidon's next turn.
```
PS: Removed the ones that where just formatting

Are we sure these are different creatures, and not just updates? I can only find one version when I search on DnDBeyond.

**Comment by chisaipete** [comment]
I have the physical books, and I see different stat blocks between monsters that were re-printed in later versions.  Not sure how to deal with this.  Maybe some kind of source-specific variants?

**Comment by Kyrremann** [comment]
Okay, then I'll just add A and B to the names, so we at least don't have the same name. And will see if we can solve this in a better way later.

**Comment by Kyrremann** [comment]
While renaming the files, I've noticed that you have used the postfix `-variant` on creatures with the same name.

See https://chisaipete.github.io/bestiary/creature/drowinquisitor and https://chisaipete.github.io/bestiary/creature/drowinquisitor-variant

If you don't mind, I'll do the same.

**Comment by chisaipete** [comment]
They do mean something else, usually it's when there is a sidebar in the text that creates a variant of a creature. I don't have an example right in front of me, but it's a specific thing.  This is like a variant but more of an alternate.
