### ISSUE TITLE
Review creature posts for extraneous information

### ISSUE THREAD

**Issue by chisaipete** [chisaipete/bestiary#65]
Side-note: check out `Augrek Brighthelm`, looks like there are too much information on that NPC/monster.

```
Roleplaying Information. Sheriff’s Ddeputy Augrek guards the southwest gate of BRyn Shander and welcomes visitors to town. She has a good heart.

Ideal: “You’ll get farther in life with a kind word than an axe”

Bond: “Bryn Shander is my home. It’s my job to protect her.”

Flaw: “I’m head over heels in love with Sheriff Southwell. One day I hope to marry him.”
```

_Originally posted by @Kyrremann in https://github.com/chisaipete/bestiary/pull/62#issuecomment-484585159_

**Comment by Kyrremann** [comment]
I looked into this a bit, and it may not be too much information: https://media.wizards.com/2016/dnd/downloads/SKT_AppD.pdf

Maybe we should just reorganise the text a bit, and create a `Roleplaying Information` header? Similar to `Action`.

**Comment by chisaipete** [comment]
Yes, I approve of this direction :)
