### ISSUE TITLE
Proofread the site

### ISSUE THREAD

**Issue by chisaipete** [chisaipete/bestiary#67]
Gah! Typo in the footer:

![image](https://user-images.githubusercontent.com/458551/56379868-99e6c480-61c5-11e9-9b1f-7c24a8fe3e25.png)

_Originally posted by @chisaipete in https://github.com/chisaipete/bestiary/pull/62#issuecomment-484605296_

**Comment by Kyrremann** [comment]
I've fixed this in #81.
