### ISSUE TITLE
Saving Throws Not Visible

### ISSUE THREAD

**Issue by jewinthewell** [chisaipete/bestiary#69]
Hi,

I'd first like to thank you for coding the bestiary; it's been extremely helpful in my 5e campaign preparations. I'm not sure if you're aware, but a creature's saving throw proficiency's are not currently displayed in their stat block. For instance, Zariel has proficiency in INT, WIS, and CHA saves, but none of these can be seen here: http://chisaipete.github.io/bestiary/creature/zariel

Creature's saving throws are visible in their Git entry, so it's not a big deal, but I thought I'd bring it to your attention if it's an unwanted bug.

Cheers

**Comment by chisaipete** [comment]
@Kyrremann did you already notice this, or did we just not catch it?

**Comment by Kyrremann** [comment]
I've totally forgot about that! I'll make a PR later tonight.
