### ISSUE TITLE
No TOA creatures?

### ISSUE THREAD

**Issue by RocksInMyDryer** [chisaipete/bestiary#71]
I searched for the Flying Monkey from Tomb of Annihilation and got no result. I'm thinking maybe the book hasn't been imported yet? I would love to help out with this, as I have some spare time, but I have no idea how to meaningfully interact with anything on github.

**Comment by Kyrremann** [comment]
If you've never used Git/Github before, there will be a bit of a steep learning curve to begin contributing. I'll link to some sources on how to get started with Git below, so you can see if you understand. Another option is to create the files on your computer, and just send them to us via e-mail or some other service.

You can see how the files look like in https://github.com/chisaipete/bestiary/tree/master/_creatures. These are generated with code based on information found in PDF/webpages. So they are not manually written. The files are written in what's called markdown.

* https://www.pluralsight.com/courses/code-school-git-real
* https://rogerdudler.github.io/git-guide/

**Comment by Yaddar01** [comment]
I am interested in contributing with the ToA monsters as well... since I also don't know about how github works, I could make the files on the computer and send them via e-mail.

do you have a specific format for the info and file extension you need for the files?

to what email should I send them?

**Comment by Kyrremann** [comment]
Great with more contributors. As of e-mail, you can probably just send them to me: kyrremann@gmail.com

The files should look like this one: https://raw.githubusercontent.com/chisaipete/bestiary/master/_creatures/aarakocra.md

Let me know if something is unclear, or you need more help. I can recommend programs like Sublime instead of Word or Notepad.

**Comment by Yaddar01** [comment]
Alright, all seems clear for now, I'll let you know if I ahve more questions

Im downloading sublime and give it a try

**Comment by Yaddar01** [comment]
Alright, I finished compiling the Beasts on ToA

the NPC's listed (like Volo or Xandala or Ras Nsi) are still pending

sent the email to you, let me know if it's correct

**Comment by Kyrremann** [comment]
Now I've created a pull request with your new beast! https://github.com/chisaipete/bestiary/pull/74

I'm guessing your using a tool to create the files, as some `1` where written as `l`, or I fixed something that wasn't wrong :p

Also, filenames need `.md` as extension, and should be small letters, and `-` in stead of ` `, but that's easy for me to fix, so no stress.

Thanks for the help!
