### ISSUE TITLE
Tomb of Annihilation creatures have malformed tags

### ISSUE THREAD

**Issue by jodoyodo** [chisaipete/bestiary#75]
The newly added Tomb of Annihilation creatures (thank you Yaddar and Kyrre!) have the tag "TOMB OF ANNIHILATION" which leads to a malformed URL when clicked on.

Example:
http://chisaipete.github.io/bestiary/creature/tri-flower-frond

When you click on the tag:
http://chisaipete.github.io/bestiary/tag/Tomb%20of%20Annihilation

The tags should be changed to be consistent with the others by replacing the spaces with hyphens, like:
http://chisaipete.github.io/bestiary/tag/out-of-the-abyss

**Comment by chisaipete** [comment]
I was about to post this as well, good catch

**Comment by Kyrremann** [comment]
Doh, I've should have tested for that, cause I was looking at the tags.
I'll fix tonight.
