### ISSUE TITLE
Saving Throws Displaying Skills

### ISSUE THREAD

**Issue by jewinthewell** [chisaipete/bestiary#76]
On the website, it looks like saving throws are degenerately referencing a creature's skills rather than their saves. Looking at the code, this seems to be the case, but I could be wrong (computer science and I don't get along).

**Comment by Kyrremann** [comment]
I see it now! The saving throws are their skill numbers. I'll fix that tonight with some other stuff. Hopefully it's only a wrong variable, and not data that I've "lost".

**Comment by jewinthewell** [comment]
I think the code is calling skills rather than saving throws:
...
<p>{{page.skills}}</p>
...
