### ISSUE TITLE
Winter Eladrin Missing Reaction

### ISSUE THREAD

**Issue by lonelywisp** [chisaipete/bestiary#83]
https://chisaipete.github.io/bestiary/creature/winter-eladrin

Missing Frigid Rebuke. Page 197 of MToF.

**Comment by lonelywisp** [comment]
Actually, all the eldarin that have reactions are missing their reactions.

https://chisaipete.github.io/bestiary/creature/summer-eladrin
https://chisaipete.github.io/bestiary/creature/autumn-eladrin

**Comment by Kyrremann** [comment]
I'll update them tonight
