### ISSUE TITLE
Default sorting should be alphabetical

### ISSUE THREAD

**Issue by chisaipete** [chisaipete/bestiary#9]
I keep stumbling on the fact that I want to browse the creatures, but the challenge-sorted list is unintuitive for looking for a name you don't know how to spell.

**Comment by chisaipete** [comment]
Let's get this sorting option on all of the category pages.  Thanks for all your work!

**Comment by Kyrremann** [comment]
I can probably add this into the #58 PR.
Do you want `sort by name` to be default sort? And then the possibility to chose `sort by CR` on all the tag-pages?

**Comment by chisaipete** [comment]
Yes, that was the thought.  I figured that the most typical search for users would be alphabetical.  i.e "Oh, what are the stats for a Foofoobeast?" not "What creatures are CR 4?"  Admittedly, being able to search for beasts which are CR X and below is useful for Druids and folks who cast Polymorph, but my gut tells me most are just looking for the reference for a specific creature, hence the thought to change it to alphabetical.

**Comment by Kyrremann** [comment]
This was solved in #58 :)
